#pragma once

#define DEBOUNCE 10

#define HOLD_ON_OTHER_KEY_PRESS
#define QUICK_TAP_TERM 0

#define LED_PIN D5

// Comment to make right half master
// #define SPLIT_HAND_MATRIX_GRID_LOW_IS_RIGHT

#define RP2040_FLASH_GD25Q64C
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_TIMEOUT 1000U
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_LED LED_PIN

#define USB_VBUS_PIN 19U
